In [6]:
# ## Exercise 1 — Group Comparison

# **Scenario:**
# You are comparing **sales for two months** to see daily trends.

# **Task:**

# 1. Create two NumPy arrays representing sales for **5 days**:

# ```python
# month1 = [200, 220, 250, 240, 260]
# month2 = [210, 230, 240, 260, 280]
# ```

# 2. Calculate the **daily difference** in sales between `month2` and `month1`.
# 3. Calculate the **percentage change** for each day.

# > Tip: Use element-wise subtraction and division. Multiply by 100 for percentage.


# ------------------------------------------------------
# 1. Create two NumPy arrays representing sales for **5 days**:

# ```python
# month1 = [200, 220, 250, 240, 260]
# month2 = [210, 230, 240, 260, 280]

import numpy as np
arr1 = np.array([200, 220, 250, 240, 260])
arr2 = np.array([210, 230, 240, 260, 280])
print(arr1)
print(arr2)

# 2. Calculate the **daily difference** in sales between `month2` and `month1`.
diff = arr2 - arr1
print(f'difference: {diff}')

# 3. Calculate the **percentage change** for each day.
perc = diff / arr1 * 100
print(f'percentage change: {perc}')

[200 220 250 240 260]
[210 230 240 260 280]
difference: [ 10  10 -10  20  20]
percentage change: [ 5.          4.54545455 -4.          8.33333333  7.69230769]


In [10]:
# Exercise 2 — 2D Dataset (Table-like Data)

# **Scenario:**
# You have weekly sales data for **3 products over 4 weeks**. Aggregation will help you analyze trends.

# **Task:**

# 1. Create a **2D NumPy array** representing sales:

# ```python
# sales_matrix = [
#     [120, 130, 140, 150],
#     [200, 210, 220, 230],
#     [90, 100, 110, 120]
# ]
# ```

# 2. Calculate:

#    * **Total sales per product**
#    * **Total sales per week**
#    * The **best-selling product** (the product with the highest total sales)

# > Tip: Use `np.sum()` with the `axis` parameter and `np.argmax()`.

# 1. Create a **2D NumPy array** representing sales:
# 3 محصول و 4 هفته
sales_matrix = [
    [120, 130, 140, 150],  # محصول 1
    [200, 210, 220, 230],  # محصول 2
    [90, 100, 110, 120]    # محصول 3
]

sales_matrix = np.array(sales_matrix)
print(sales_matrix)

# 2. Calculate:

#    * **Total sales per product**
total_sales_per_product = np.sum(sales_matrix, axis=1)
print(f'total_sales_per_product: {total_sales_per_product}')


#    * **Total sales per week**
total_sales_per_week = np.sum(sales_matrix, axis=0)
print(f'total_sales_per_week: {total_sales_per_week}')


#    * The **best-selling product** (the product with the highest total sales)
best_selling_product = np.argmax(total_sales_per_product)
print(f'best_selling_product: {best_selling_product}')

[[120 130 140 150]
 [200 210 220 230]
 [ 90 100 110 120]]
total_sales_per_product: [540 860 420]
total_sales_per_week: [410 440 470 500]
best_selling_product: 1


In [13]:

## Exercise 3 — Analytical Filtering

# **Scenario:**
# You have a list of **product prices** and want to filter for specific price ranges.

# **Task:**

# 1. Create a NumPy array of prices:

# ```python
# prices = [30, 60, 90, 120, 150, 180]
# ```

# 2. Filter the prices that are:

#    * Greater than 100
#    * Between 50 and 150 (inclusive)

# > Tip: Use boolean indexing with conditions like `prices > 100` or `(prices >= 50) & (prices <= 150)`.


# 1. Create a NumPy array of prices:
prices = np.array([30, 60, 90, 120, 150, 180])
print(prices)

# 2. Filter the prices that are:
#    * Greater than 100
filtered_prices_1 = prices[prices > 100]
print(f'prices greater than 100: {filtered_prices_1}')
#    * Between 50 and 150 (inclusive)
filtered_prices_2 = prices[(prices >= 50) & (prices <= 150)]
print(f'prices between 50 and 150 (inclusive): {filtered_prices_2}')



[ 30  60  90 120 150 180]
prices greater than 100: [120 150 180]
prices between 50 and 150 (inclusive): [ 60  90 120 150]


In [17]:
# Exercise 4 — Using `np.where` (Customer Segmentation)

# **Scenario:**
# You want to classify customers into groups based on their age. This is a common task in analytics for segmentation.

# **Task:**

# 1. Create a NumPy array of **customer ages**:

# ```python
# ages = [18, 22, 25, 30, 35, 40, 45, 50]
# ```

import numpy as np
ages = np.array([18, 22, 25, 30, 35, 40, 45, 50])
print(ages)

# 2. Create a new array `age_group` with the following rules:

#    * `"Young"` if age < 30
#    * `"Adult"` if age >= 30

age_group = np.where(ages < 30, "Young", "Adult")
print(age_group)

# 3. Count how many customers are `"Young"` and how many are `"Adult"`.
num_young = np.sum(age_group == "Young")
num_adult = np.sum(age_group == "Adult")
print(f"Number of Young: {num_young}")
print(f"Number of Adult: {num_adult}")  

# > Tip: Use `np.where()` for conditional assignment, and `np.sum()` for counting.


[18 22 25 30 35 40 45 50]
['Young' 'Young' 'Young' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
Number of Young: 3
Number of Adult: 5
